### ISSUE TITLE
bug None en match_workspace

### ISSUE THREAD

**Issue by darcosion** [boringthegod/postmaniac#1]
Il sembleray que l'on puisse avoir des `None` en retour de liste de workspace : 
```
  File "~/postmaniac/postmaniac.py", line 140, in <module>
    worksp = match_workspace.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by boringthegod** [comment]
Merci pour la remontée du bug

C'est fix [ici](https://github.com/boringthegod/postmaniac/commit/45fe4f2020c74dd332294b2bccc0db364822a73f)
